#!/usr/bin/env sh
#
# Some sane defaults for sending notifications.
#

set -eu

message=""
option_help=false
usage="USAGE:
    $(basename "$0") [options]

DESCRIPTION:
    Send a desktop notification to a notification daemon such as mako.

OPTIONS:
    --help, -h        Show this help text
    --message, -m     Notification message"

for arg in "$@"; do
  case $arg in
  -h | --help)
    option_help=true
    shift
    ;;
  *)
    message="$message $1"
    shift
    ;;
  esac
done

if [ "$option_help" = true ]; then
  echo "$usage"
  exit 0
fi

notify-send -t 5000 --urgency=low --icon=gtk-dialog-info "$message"
