#!/usr/bin/env sh

shell='zsh'
terminal='kitty'

if [ "$1" = "windows" ]; then
	swaymsg -t get_tree | jq -r 'recurse(.nodes[]?)|recurse(.floating_nodes[]?)|select(.type=="con"),select(.type=="floating_con")|(.id|tostring)+" "+.app_id+" -> "+.name' | fzf | awk '{print $1}' | xargs -I % "$shell" 'swaymsg [con_id=%] focus'
else
	options=$(echo -n "$PATH" | xargs -d: -I{} -r -- find -L {} -maxdepth 1 -mindepth 1 -name ".*" -prune -o -name "[" -prune -o -executable -printf "%f\n" 2>/dev/null | sort -ufd)
	kitty --hold -- zsh -c "echo $options | fzf"
fi
