right_format = """
$rust\
$nodejs\
$lua\
$git_status\
$git_branch\
$aws\
$cmd_duration """

format = """
$directory\
$nix_shell\
$jobs\
$line_break\
$character"""

[aws]
disabled = true
format = "[· ](black) [($symbol$profile$region)]($style)"
symbol = " "
style = "bright-black"

[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"
vicmd_symbol = "[](bold yellow)"

[cmd_duration]
format = "[· ](black)[ $duration]($style)"
style = "black"

[directory]
style = "bold blue"
read_only = " "
read_only_style = "bright-black"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[ $conflicted$ahead$behind$untracked$modified]($style)"
style = "black"
ahead = " "
behind = " "
conflicted = " "
untracked = " "
modified = " "

[golang]
symbol = " "

[jobs]
format = "[$symbol$number]($style)"
style = "black"
symbol = "祈"
number_threshold = 2
symbol_threshold = 1

[lua]
format = "[ $version](black)[ · ](black)"
version_format = "$raw"

[nix_shell]
format = '[\$ $name](black) '

[nodejs]
format = '[ $version](black)[ · ](black)'
version_format = "$raw"

[rust]
format = '[( $version)](black)[ · ](black)'
version_format = "$raw"
