#!/usr/bin/env sh

##
# RIVER WM STARTUP
#
# Sets up the environment before launching River.
##

# Script paths organized and prefixed by category: `nix/nix-preview`, `launch/launch-app`, etc.
for directory in ~/.scripts/*; do
  export PATH="$PATH:$directory"
done

# Firefox
export MOZ_DBUS_REMOTE=1
export MOZ_USE_XINPUT2=1

# GTK
export GTK_THEME="Catppuccin-Latte-Yellow"
export GTK_USE_PORTAL=1

# River
export GDK_BACKEND="wayland"
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export SDL_VIDEODRIVER="wayland"
export XDG_CURRENT_DESKTOP="river"
export XDG_SESSION_DESKTOP="river"
export XDG_SESSION_TYPE="wayland"

# Java
export _JAVA_AWT_WM_NONREPARENTING=1

# Keyboard
export XKB_DEFAULT_LAYOUT="us,se"
export XKB_DEFAULT_OPTIONS="shift:both_capslock,grp:ctrls_toggle,lv3:ralt_switch_multikey"

# Start and output to disk
logfile="$HOME/.local/share/logs/river.log"
bakfile="$logfile.bak"

if [ -f "$bakfile" ]; then
  rm -f "$bakfile" >/dev/null 2>&1
fi

if [ -f "$logfile" ]; then
  mv "$logfile" "$bakfile" >/dev/null 2>&1
fi

river 2>"$logfile"
