#!/usr/bin/env sh

##
# RIVER WM STARTUP
#
# Sets up the environment before launching River.
##

export NX_RIVER_LOGFILE="$HOME/.local/share/logs/river.log"

# Script paths organized and prefixed by category: `nix/nix-preview`, `launch/launch-app`, etc. We
# want to add these to PATH before launching River so it can spawn the scripts.
for directory in ~/.scripts/*; do
  export PATH="$PATH:$directory"
done

# Start and output to disk
logfile="$HOME/.local/share/logs/river.log"
bakfile="$logfile.bak"

if [ -f "$bakfile" ]; then
  rm -f "$bakfile" >/dev/null 2>&1
fi

if [ -f "$logfile" ]; then
  mv "$logfile" "$bakfile" >/dev/null 2>&1
fi

dbus-run-session -- river 2>"$logfile"
